"""Pyfii Choreo Agent — CLI 原型"""
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO_ROOT / "tools" / "choreo_agent"))

from core import Session


def main():
    if len(sys.argv) < 2:
        print("Usage: python tools/choreo_agent/main.py agent_projects/<name>")
        return

    proj = Path(sys.argv[1])
    if not proj.is_absolute():
        proj = REPO_ROOT / proj
    proj = proj.resolve()

    if not (proj / "state.json").exists():
        print(f"No state.json in {proj}. Run init first.")
        return

    session = Session(proj)
    print(f"Project: {session.state.name}")
    print(f"Music: {session.state.music_path} ({session.state.music_duration}s)")
    print(f"Mode: {session.state.mode}")
    print(f"Locked: {session.state.locked_segment_ids}")

    while True:
        seg = session.state.current_segment
        if seg:
            print(f"\nCurrent: {seg.id} ({seg.start_time}-{seg.end_time}s) "
                  f"[{'locked' if seg.locked else 'unlocked'}]")
        else:
            print("\nAll segments done.")

        raw_cmd = input("> ").strip()
        cmd = raw_cmd.lower()
        if not cmd:
            continue

        if cmd == "q":
            session.save()
            break

        elif cmd == "v":
            result = session.validate()
            print(f"compile={result.compile_ok} run={result.run_ok}")
            print(f"dist={result.distance_warnings} act={result.action_warnings}")
            print(f"minD={result.min_distance_cm}cm dense={result.dense_min_distance_cm}cm XY={result.xy_span}")
            print(f"continuity_required={result.continuity_required} hover_ok={result.hover_check_ok} hover={result.hover_segments[:3]}")
            print(f"motion={result.motion_start_s}-{result.motion_end_s}s envelope_ok={result.motion_envelope_ok}")
            if result.motion_envelope_errors:
                print(f"motion_errors={result.motion_envelope_errors[:3]}")
            if result.collision_intervals:
                print(f"collisions={result.collision_intervals[:3]}")
            if result.error_message:
                print(f"error: {result.error_message[-200:]}")
            if result.continuity_error:
                print(f"continuity_error: {result.continuity_error[-200:]}")

        elif cmd == "a":
            if session.approve_and_lock():
                print(f"Locked {session.state.locked_segment_ids[-1]}")
            else:
                print("Approve failed — validate first?")

        elif cmd.startswith("g"):
            feedback = raw_cmd[1:].strip()
            try:
                rounds = session.generate_until_safe_with_llm(
                    provider="deepseek",
                    feedback=feedback,
                    max_attempts=5,
                )
            except Exception as e:
                print(f"Generate failed: {e}")
                continue
            if not rounds or rounds[-1].response is None:
                print("Generate failed. Segment locked or empty response.")
                continue

            for round_result in rounds:
                response = round_result.response
                validation = round_result.validation
                if response is None:
                    print(f"Round {round_result.index}: generation failed.")
                    continue
                print(f"Round {round_result.index}: generated by {response.model}.")
                if response.input_tokens or response.output_tokens:
                    print(f"  tokens in={response.input_tokens} out={response.output_tokens}")
                if validation is not None:
                    print(f"  compile={validation.compile_ok} run={validation.run_ok} read={validation.read_fii_ok}")
                    print(f"  dist={validation.distance_warnings} act={validation.action_warnings} passed={validation.passed}")
                    print(f"  minD={validation.min_distance_cm}cm dense={validation.dense_min_distance_cm}cm XY={validation.xy_span}")
                    print(f"  continuity_required={validation.continuity_required} hover_ok={validation.hover_check_ok} hover={validation.hover_segments[:3]}")
                    print(f"  motion={validation.motion_start_s}-{validation.motion_end_s}s envelope_ok={validation.motion_envelope_ok}")
                    if validation.motion_envelope_errors:
                        print(f"  motion_errors={validation.motion_envelope_errors[:3]}")
                    if validation.collision_intervals:
                        print(f"  collisions={validation.collision_intervals[:3]}")
                    if validation.error_message:
                        print(f"  error: {validation.error_message[-200:]}")
                    if validation.continuity_error:
                        print(f"  continuity_error: {validation.continuity_error[-200:]}")

            if rounds[-1].validation and rounds[-1].validation.passed:
                print("Safe gate passed. You can approve and lock this segment.")
            else:
                print("Safe gate failed. Segment remains unlocked; do not advance.")

        elif cmd == "h":
            print(session.handoff())

        elif cmd == "s":
            session.save()
            print("Saved.")

        elif cmd == "sync":
            session.sync_state_with_markers(save=True)
            print("Synced state from design.py markers.")

        else:
            print("Commands: g [feedback]=generate+repair v=validate a=approve h=handoff sync s=save q=quit")


if __name__ == "__main__":
    main()
