[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pyfii"
dynamic = ["version"]
authors = [
  { name="Kevin0412", email="kevin0412_xlt@qq.com" },
  { name="miaooo0000OOOO", email="1683618861@qq.com"}
]
description = "这个库可以让我们用python写Fii的无人机程序，有三视图模拟飞行的功能，模拟飞行更方便观看"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: OS Independent",
]
dependencies = ["opencv-python>=4.10.0.84",
"pyqt5",
"tqdm",
"numpy>=1.26,<3",
"pygame",
"ffmpy",
"joblib>=1.4"]

[project.urls]
"Homepage" = "https://github.com/Kevin0412/pyfii"
"Bug Tracker" = "https://github.com/Kevin0412/pyfii/issues"

[tool.setuptools.dynamic]
version = {attr = "pyfii.__version__"}
